=== darouwan/DataService/xml/holiday.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT HOLIDAYLIST (STATE+)>
<!ELEMENT STATE (HOLIDAY+)>
<!ELEMENT HOLIDAY (TITLE,MONTH,DAY,WEEKDAY,YEAR)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT MONTH (#PCDATA)>
<!ELEMENT DAY (#PCDATA)>
<!ELEMENT WEEKDAY (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>


<!ATTLIST STATE NAME CDATA #REQUIRED>

=== darouwan/DataService/xml/holidays.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HOLIDAYLIST SYSTEM "D:/workspace/DataService/xml/holiday.dtd" >
<HOLIDAYLIST>
	<STATE value="NSW">
		<HOLIDAY>
			<TITLE>New Year's Day</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Sunday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>

		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Additional Day</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>2</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Australia Day </TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>28</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Good Friday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>6</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>29</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Saturday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>30</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Sunday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>8</DAY>
				<WEEKDAY>Sunday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>31</DAY>
				<WEEKDAY>Sunday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Monday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>9</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Anzac Day</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Queen's Birthday </TITLE>
			<YEAR value="2012">
				<MONTH>June</MONTH>
				<DAY>11</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>June</MONTH>
				<DAY>10</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Bank Holiday</TITLE>
			<YEAR value="2012">
				<MONTH>August</MONTH>
				<DAY>6</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>August</MONTH>
				<DAY>5</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Labour Day</TITLE>
			<YEAR value="2012">
				<MONTH>October</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>October</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Christmas Day public holiday</TITLE>
			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Boxing Day</TITLE>

			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
	</STATE>
	<STATE value="NT">
		<HOLIDAY>
			<TITLE>New Year's Day</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>2</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>

		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Additional Day</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Sunday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Australia Day </TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>28</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Good Friday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>6</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>29</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Saturday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>30</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Monday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>9</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Anzac Day</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Queen's Birthday </TITLE>
			<YEAR value="2012">
				<MONTH>June</MONTH>
				<DAY>11</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>June</MONTH>
				<DAY>10</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Bank Holiday</TITLE>
			<YEAR value="2012">
				<MONTH>August</MONTH>
				<DAY>6</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>August</MONTH>
				<DAY>5</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Labour Day</TITLE>
			<YEAR value="2012">
				<MONTH>October</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>October</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Christmas Day public holiday</TITLE>
			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Boxing Day</TITLE>

			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
	</STATE>
	<STATE value="QLD">
		<HOLIDAY>
			<TITLE>New Year's Day</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Sunday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>

		</HOLIDAY>
		<HOLIDAY>
			<TITLE>2 January</TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>2</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Australia Day </TITLE>
			<YEAR value="2012">
				<MONTH>January</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>January</MONTH>
				<DAY>28</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Good Friday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>6</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>29</DAY>
				<WEEKDAY>Friday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Saturday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>March</MONTH>
				<DAY>30</DAY>
				<WEEKDAY>Saturday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Easter Monday</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>9</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Anzac Day</TITLE>
			<YEAR value="2012">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>April</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Queen's Diamond Jubilee</TITLE>
			<YEAR value="2012">
				<MONTH>June</MONTH>
				<DAY>11</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>

		</HOLIDAY>

		<HOLIDAY>
			<TITLE>Queen's Birthday</TITLE>
			<YEAR value="2012">
				<MONTH>October</MONTH>
				<DAY>1</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>October</MONTH>
				<DAY>7</DAY>
				<WEEKDAY>Monday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Royal Queen'sland Show</TITLE>
			<YEAR value="2012">
				<MONTH>August</MONTH>
				<DAY>15</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>August</MONTH>
				<DAY>14</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
		</HOLIDAY>

		<HOLIDAY>
			<TITLE>Christmas Day</TITLE>
			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Tuesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>25</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
		<HOLIDAY>
			<TITLE>Boxing Day</TITLE>

			<YEAR value="2012">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Wednesday</WEEKDAY>
			</YEAR>
			<YEAR value="2013">
				<MONTH>December</MONTH>
				<DAY>26</DAY>
				<WEEKDAY>Thursday</WEEKDAY>
			</YEAR>
		</HOLIDAY>
	</STATE>
	<STATE value="VIC">
